# Generated by Django 5.0.2 on 2024-02-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks1', '0002_users_remove_todo_id_todo_todoid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='todo',
            name='ToDoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
