# Generated by Django 5.0.2 on 2024-02-16 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks1', '0003_rename_users_user_alter_todo_todoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DOB',
            new_name='DateOB',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='ToDoId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserId',
        ),
        migrations.AddField(
            model_name='todo',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tasks1.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
