# Generated by Django 5.0.2 on 2024-02-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks1', '0004_rename_dob_user_dateob_remove_todo_todoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='UserId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='DateOB',
            field=models.DateField(),
        ),
    ]
