# Generated by Django 5.0.2 on 2024-02-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks1', '0005_remove_todo_creator_remove_user_id_user_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tasks1.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='ToDoId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
