# Generated by Django 5.0.2 on 2024-02-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks1', '0006_remove_todo_id_todo_creator_todo_todoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='ToDoId',
        ),
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
